sudo: false
language: node_js
node_js:
  - 8
  - 9
  - 10
cache:
  directories:
  - "$HOME/.npm"
after_success:
  - npx nyc report --reporter=lcov | npx codecov --file=./coverage/lcov.info
  - npm run cov:check